query FullCourses {
    allCourses {
        id
        name
        courseNickname
        term {
            endAt
            startAt
            name
            id
        }
        assignmentsConnection {
            nodes {
                description
                courseId
                dueAt
                createdAt
                id
                name
                position
                updatedAt
            }
        }
        modulesConnection {
            nodes {
                name
                id
                moduleItems {
                    content {
                        ... on File {
                            __typename
                            _id
                            displayName
                            createdAt
                            updatedAt
                            url
                            size
                            mimeClass
                            contentType
                        }
                        ... on Page {
                            __typename
                            _id
                            title
                            updatedAt
                            createdAt
                        }
                    }
                }
            }
        }
    }
}

query BareCourses {
    allCourses {
        id
        name
        courseNickname
        term {
            endAt
            startAt
            name
            id
        }
    }
}